config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :skip => :registration

  resources :posts do 
  	resources :comments
  end

  resources :categories
  resources :admin, only: [:index]
  
  root 'posts#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :category
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	layout 'admin'

	def index
		@posts = Post.all.order('created_at DESC')
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@categories = Category.all.order('created_at DESC')
		render layout: 'admin'
	end

	def new
		@category = Category.new
		render layout: 'admin'
	end

	def create
		@category = Category.new(category_params)

		if @category.save
			redirect_to categories_path
		else
			render 'new'
		end
	end

	def edit
		@category = Category.find_by(params[:id])
		render layout: 'admin'
	end

	def update
		@category = Category.find_by(params[:id])

		if @category.update(category_params)
			redirect_to categories_path
		else
			render 'edit'
		end
	end

	def destroy
		@category = Category.find(params[:id])
		@category.destroy
		redirect_to categories_path
	end






	private
		def category_params
			params.require(:category).permit(:name)
		end
		
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
	before_action :authenticate_user!, except: [:index, :show]
 

	def index
		if params[:category].blank?
			@posts = Post.all.order('created_at DESC')
		else
			@category_id = Category.find_by(name: params[:category]).id
			@posts = Post.where(category_id: @category_id).order('created_at DESC')
		end
		

	end

	def new 
		@post = Post.new

		render layout: 'admin'
	end 

	def create
		@post = Post.new(post_params)
		
		if @post.save
			redirect_to admin_index_path
		else
			render 'new'
		end
	end 

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
		render layout: 'admin'
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end

	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to admin_index_path

	end




	private

	def post_params
		params.require(:post).permit(:title, :body, :category_id)
	end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/index.html.erb
<% @posts.each do |post| %>
	<div class="row">
	  <div class="col-sm-6 col-md-4">
	    <div class="thumbnail">
	     
	      <div class="caption">
	     
				
	   			<h3><%= link_to post.title, post %></h3>

	        <p><%= post.body.html_safe %></p>
			
	     
	        <p>
		        <div href="#" class="btn btn-default" role="button"><%= link_to 'edit', edit_post_path(post) %></div> 
		        <div href="#" class="btn btn-default" role="button"><%= link_to 'Delete', post_path(post), method: :delete, data: {confirm: 'Are you sure?'} %></div>
	        </p>
	      </div>
	    </div>
	  </div>
	</div>
<% end %>

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
	<p>
		Category:<br>
		<%= f.text_field :name %>
	</p>


	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/categories/edit.html.erb
<h1>Edit category</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1>all Category</h1>
<% @categories.each do |category| %>
	<div class="row">
	  <div class="col-sm-6 col-md-4">
	    <div class="thumbnail">	     
	      <div class="caption">
	   			<h3><%= category.name %> </h3>

	        <p>
		        <div href="#" class="btn btn-default" role="button"><%= link_to 'edit', edit_category_path(category) %></div> 
		        <div href="#" class="btn btn-default" role="button"><%= link_to 'delete', category_path(category), method: :delete, data: {confirm: 'Are you sure?'} %></div>
	        </p>
	      </div>
	    </div>
	  </div>
	</div>
	<% end %>

app/views/categories/new.html.erb
<h1>Category</h1>
<p>
	<%= render 'form' %>
</p>

app/views/comments/_comment.html.erb
<div class="comment">
	<div class="name">
		<%= comment.name %>
	</div>

	<div class="comment-body">
		<%= comment.body %>
	</div>
	<% if user_signed_in? %>
	<%= link_to 'Delete', [comment.post, comment], method: :delete, class: "button", data: {confirm: 'Are you sure? '} %>
	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<p>
		Name:<br>
		<%= f.text_field :name, size: "75" %>
	</p>

	<p>
		Comment:<br>
		<%= f.text_area  :body, size: "75 x 10", placeholder: "say something..." %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jimmy's Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
</head>

<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      
      <div class="navbar-brand"><%= link_to 'Admin', admin_index_path %></div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'All categories', categories_path %></li>
        <li><%= link_to 'New category', new_category_path %></li>
        <li><%= link_to 'All posts', admin_index_path %></li>
        <li><%= link_to 'New Post', new_post_path %></li>
       
      </ul>
    
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home Page', root_path %></li>
        <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
	<%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jimmy's Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
</head>
<body>
	<div id="main-body">
		<nav class="navbar ">
			<div class="container-fluid">
				<div id="nav">
			<div class="navbar-left">
				<ul class="nav navbar-nav navbar-left">
				<li><%= link_to "Jimmy's Blog", root_path %></li>
					
				</ul>
			</div>
			<div class="navbar-right">
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to 'Home', root_path %></li>
					<% if user_signed_in? %>
						<li><%= link_to 'Admin', admin_index_path %></li>
					<% end %>
				</ul>
			</div>
		</div>
			</div>
		</nav>

		<!-- 
		<div class="alert alert-info" role="alert"><%= notice %></div>
		<div class="alert alert-warning" role="alert"><%= alert %></div>
		 -->

	<div id="sidebar">
		<div class="sidebar-content">
			<div class="sidebar-title">Category</div>
			<% Category.all.each do |category| %>
			<ul class="category-list">
				<li><%= link_to category.name, posts_path(category: category.name) %></li>
			</ul>
	  	<% end %>
	  </div>
	  
	</div>


<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>

		<%= yield %>

	</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<div class="alert alert-info" role="alert">
			<h2><%= pluralize(@post.errors.count,"error") %> prevented this post from saving</h2>
				<ul>
					<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
					<% end %>
				</ul>
		</div>
	<% end %> 
	<p>
		choice category:<br>
		<%= f.collection_select :category_id, Category.all, :id, :name %>
	</p>
	<p>
		Title:<br>
		<%= f.text_field :title, size: "100" %>
	</p>

	<p>
		Body:<br>
		<%= f.text_area :body, :class => "tinymce", size: "40 x 20 "%>
		<%= tinymce %>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<div id="main-post">
		<div class="post">
			<div class="post-header">
				<div class="title">
					<%= link_to post.title, post %>
					<div class="post-info">
					<%= post.created_at.strftime("%Y-%m-%d %H:%M") %>
					</div>
				</div>

				
			</div>
			<div class="body">
				<%= post.body.truncate(300).html_safe%>
			</div>
			<div class="btn-group" role="group" >
  			<button type="button" class="btn btn-default"><%= link_to 'Read more', post %></button>
  		</div>
		</div>
	</div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<div id="main-post">
	<div class="post">
		<div class="post-header">
			<div class="title">
				<%= @post.title %>
				<div class="post-info">
				<%= @post.created_at.strftime("%Y-%m-%d %H:%M") %>
				</div>
			</div>

			
		</div>
		<div class="body">
			<%= @post.body.html_safe %>
		</div>
	</div>

	


	Total <%= @post.comments.count %> comments

	<hr>
	<div class="comments">
	<%= render @post.comments %>
	</div>
	add a comment:
	<%= render 'comments/form' %>
	

</div>